name: 'Infrastructure Setup'

on:
  push:
    branches:
    - main
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select environment'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - prod

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}
      ENVIRONMENT: ${{ github.event.inputs.environment }}

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v4
        
    # Setup Terraform
    - name: Save PrivateKey
      run: |
        ls -ltra
        echo ${{ secrets.VM_PUBLIC_KEY }} > terraform/id_rsa.pub

    # Setup Terraform
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.5.7

    # Initialize Terraform
    - name: Terraform Init
      run: terraform init
      working-directory: terraform

    # Validate Terraform configuration
    - name: Terraform Validate
      run: terraform validate
      working-directory: terraform

    # Format Terraform files
    - name: Terraform Format
      run: terraform fmt -check
      working-directory: terraform

    # Plan Terraform deployment
    - name: Terraform Plan
      run: terraform plan -out=tfplan
      working-directory: terraform

    # Apply Terraform configuration (only on push to main)
    - name: Terraform Apply
      working-directory: terraform
      run: |
       if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
          terraform apply -auto-approve --var-file="terraform-${{ github.event.inputs.environment }}.tfvars" tfplan
       else
          terraform apply -auto-approve --var-file="terraform-dev.tfvars" tfplan
       fi  

    # Apply Terraform configuration (only on push to main)
    # - name: Terraform Apply
      # run: terraform apply -auto-approve tfplan
      # run: terraform apply -var="enviornment=dev" --auto-approve tfplan
      # run: terraform apply -auto-approve --var-file="terraform-dev.tfvars" tfplan
      # working-directory: terraform
